'use client';
import dynamic from 'next/dynamic';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Check, ChevronRight, Flame, Gauge, Headphones, Menu, Phone, ShieldCheck, Truck, X, Wrench } from 'lucide-react';
import { company, products, services, whatsappUrl } from '@/lib/config';
import { cylinderSizes } from '@/types/order';

const HeroScene = dynamic(() => import('@/components/three/HeroScene'), { ssr: false, loading: () => <div aria-label="Loading interactive LPG cylinder" /> });
const iconSet = [Flame, Truck, Gauge, ShieldCheck, Headphones, Wrench];

export default function Home() {
  const [selected, setSelected] = useState(2);
  const [menuOpen, setMenuOpen] = useState(false);
  const [status, setStatus] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const productStageRef = useRef<HTMLDivElement>(null);
  const [productReady, setProductReady] = useState(false);
  useEffect(() => { let cleanup: (() => void) | undefined; import('@/lib/animations').then(({ initPageAnimations }) => { cleanup = initPageAnimations(); }); return () => cleanup?.(); }, []);
  useEffect(() => {
    const stage = productStageRef.current;
    if (!stage) return;
    const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { setProductReady(true); observer.disconnect(); } }, { rootMargin: '280px' });
    observer.observe(stage);
    return () => observer.disconnect();
  }, []);
  const product = products[selected];
  const orderLink = whatsappUrl(`Hello ${company.name}, I would like to order a ${product.size} LPG refill.`);
  async function submitOrder(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSubmitting(true); setStatus('');
    const form = new FormData(event.currentTarget);
    const payload = { name: form.get('name'), phone: form.get('phone'), cylinderSize: form.get('cylinderSize'), message: form.get('message') };
    const response = await fetch('/api/orders', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) });
    setSubmitting(false);
    if (response.ok) {
      const whatsappMessage = `Hello ${company.name}, I would like to place an LPG refill order.\n\nName: ${payload.name}\nPhone: ${payload.phone}\nCylinder size: ${payload.cylinderSize}\nMessage: ${payload.message}`;
      window.open(whatsappUrl(whatsappMessage), '_blank', 'noopener,noreferrer');
      setStatus('WhatsApp opened with your order details. Tap Send to complete the order.');
      event.currentTarget.reset();
    } else { const result = await response.json(); setStatus(result.error || 'Please check your details and try again.'); }
  }
  return <main>
    <nav className="nav-shell"><div className="nav-inner"><a href="#home" className="brand">AL-SHAHERYAR <span>ENTERPRISES</span></a><div className="nav-links"><a href="#home">HOME</a><a href="#about">ABOUT</a><a href="#services">SERVICES</a><a href="#products">PRODUCTS</a><a href="#contact">CONTACT</a></div><a className="nav-cta" href={orderLink}>ORDER NOW <ArrowUpRight size={15} /></a><button className="mobile-toggle" aria-label="Toggle navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <div className="nav-links" style={{ display: 'grid', padding: '20px 0 8px' }}><a href="#home" onClick={() => setMenuOpen(false)}>HOME</a><a href="#about" onClick={() => setMenuOpen(false)}>ABOUT</a><a href="#services" onClick={() => setMenuOpen(false)}>SERVICES</a><a href="#products" onClick={() => setMenuOpen(false)}>PRODUCTS</a><a href="#contact" onClick={() => setMenuOpen(false)}>CONTACT</a></div>}</nav>
    <section className="hero" id="home"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow">LPG REFILL · DOORSTEP DELIVERY</div><h1>Gas refill,<br /><em>delivered</em> to your doorstep.</h1><p>Fast, safe and reliable LPG cylinder refill and doorstep delivery service for homes and businesses.</p><div className="actions"><a className="button red" href={orderLink}>ORDER ON WHATSAPP <ArrowUpRight size={16} /></a><a className="button outline" href={company.phoneHref}><Phone size={16} /> CALL NOW</a></div><div className="trust-mini"><div><span>✓</span>100% SAFE</div><div><span>✓</span>PURE WAZAN</div><div><span>✓</span>FAST DELIVERY</div><div><span>✓</span>24/7 SUPPORT</div></div></div><div className="hero-stage"><HeroScene /></div></div></section>
    <section className="trust-strip"><div className="trust-item"><ShieldCheck className="icon-box" size={20} /><strong>100% Safe</strong><span>Tested before it leaves us</span></div><div className="trust-item"><Gauge className="icon-box" size={20} /><strong>Pure Wazan</strong><span>Accurate quantity, every time</span></div><div className="trust-item"><Truck className="icon-box" size={20} /><strong>Fast Delivery</strong><span>At your door, when you need it</span></div><div className="trust-item"><Headphones className="icon-box" size={20} /><strong>24/7 Support</strong><span>Real help from real people</span></div></section>
    <section className="section" id="about"><div className="container about-grid"><div className="about-copy reveal"><div className="kicker">Who we are</div><h2>Reliable gas service,<br />made local.</h2><p>AL-SHAHERYAR ENTERPRISES provides LPG refill and doorstep delivery services focused on safety, reliability, accurate quantity, convenience and fast service.</p><p>Whether you are keeping a home running or supplying a busy kitchen, our job is to make your refill simple and dependable.</p></div><div className="about-mark reveal"><strong>AS</strong><p>Professional LPG service for the moments when you need fuel you can trust.</p><a className="button light" href={orderLink}>PLACE AN ORDER <ChevronRight size={16} /></a></div></div></section>
    <section className="section services-section" id="services"><div className="container"><div className="section-head reveal"><div><div className="kicker">What we do</div><h2>Service built around<br />your peace of mind.</h2></div><p>From a quick top-up to a regular commercial supply, every refill is handled with attention to safety and accuracy.</p></div><div className="services-grid">{services.map(([number, title, description], index) => { const Icon = iconSet[index]; return <article className="service-card" key={title}><span className="service-number">{number}</span><Icon className="icon-box" size={24} /><h3>{title}</h3><p>{description}</p></article>; })}</div></div></section>
    <section className="section process"><div className="container"><div className="section-head reveal"><div><div className="kicker">Simple from start to finish</div><h2>Get your LPG refill<br />in 3 easy steps.</h2></div><p>No queues, no guesswork. Just a clear order and dependable delivery.</p></div><div className="steps">{[['01','Place Your Order','Message us on WhatsApp or call our team.'],['02','Safe & Accurate Refill','We inspect, test and fill your cylinder correctly.'],['03','Delivered To Your Door','Your refill arrives ready for your kitchen or business.']].map(([num,title,desc]) => <div className="step reveal" key={num}><span className="step-no">STEP {num}</span><h3>{title}</h3><p>{desc}</p></div>)}</div></div></section>
    <section className="section products" id="products"><div className="container"><div className="section-head reveal"><div><div className="kicker">Choose your size</div><h2>Refill exactly<br />what you need.</h2></div><p>Every size is available for refill. Contact us for the current price and availability.</p></div><div className="product-layout"><div className="product-stage" ref={productStageRef}>{productReady ? <HeroScene scale={product.scale * 0.8} /> : <div className="product-scene-placeholder" aria-label="Product scene loads when visible" />}<span className="product-label">ANIMATED CYLINDER · {product.size}</span></div><div><div className="product-list">{products.map((item, index) => <button className={`product-pill ${selected === index ? 'selected' : ''}`} key={item.size} onClick={() => setSelected(index)}><strong>{item.size}</strong><span>Refill</span></button>)}</div><div className="product-info"><div className="kicker">Selected cylinder</div><h3>{product.size} LPG refill</h3><p>{product.detail}. Current price available on request.</p><a className="button red" href={orderLink}>ORDER THIS SIZE <ArrowUpRight size={16} /></a></div></div></div></div></section>
    <section className="section safety"><div className="container safety-grid"><div className="reveal"><div className="shield"><ShieldCheck /></div></div><div className="reveal"><div className="kicker">Safety, always</div><h2>Your safety<br />comes first.</h2><p>Our process is built around the details that matter: every cylinder is inspected, leakage checked, filled correctly and handled safely.</p><div className="safety-list"><div><strong>Inspect</strong><span>We check the cylinder condition before filling.</span></div><div><strong>Leakage check</strong><span>Connections and valves are carefully tested.</span></div><div><strong>Proper filling</strong><span>Measured quantities, with pure wazan.</span></div><div><strong>Safe handling</strong><span>Delivered upright and ready to use.</span></div></div><p style={{ fontWeight: 700, color: 'var(--dark)', marginTop: 28 }}>Always keep LPG cylinders upright and away from heat or open flames.</p></div></div></section>
    <section className="order-band"><div className="container"><div><h2>Need an LPG refill?</h2><p>Place your order today and get reliable LPG service delivered to your doorstep.</p></div><div className="actions"><a className="button light" href={orderLink}>ORDER ON WHATSAPP <ArrowUpRight size={16} /></a><a className="button outline" href={company.phoneHref}><Phone size={16} /> CALL NOW</a></div></div></section>
    <section className="section" id="contact"><div className="container contact-grid"><div className="contact-copy reveal"><div className="kicker">Get in touch</div><h2>Let’s get your<br />cylinder sorted.</h2><p>Share your details and we will follow up to confirm your order. For the fastest response, message us on WhatsApp.</p><div className="contact-line"><Phone size={19} color="var(--red)" /> {company.phoneDisplay}</div></div><form className="order-form reveal" onSubmit={submitOrder}><label>Name<input name="name" required placeholder="Your name" /></label><label>Phone<input name="phone" required placeholder="+92 ..." /></label><label>Cylinder size<select name="cylinderSize" defaultValue="11.8 KG">{cylinderSizes.map((size) => <option key={size}>{size}</option>)}</select></label><label>Message<input name="message" required placeholder="How can we help?" /></label>{status && <div className="form-status">{status}</div>}<button className="button red full" disabled={submitting}>{submitting ? 'SENDING...' : 'SEND TO WHATSAPP'} <ArrowUpRight size={16} /></button></form></div></section>
    <section className="other"><div className="container"><div><h3>Explore Our Other Business</h3><p>Looking for reliable electronics repair or refurbished LCDs? Explore our other business dedicated to electronic repair and refurbished LCD solutions.</p></div><a className="button outline" style={{ color: 'var(--dark)', borderColor: '#073b7844' }} href={company.otherBusinessUrl}>VISIT {company.otherBusinessName.toUpperCase()} <ArrowUpRight size={16} /></a></div></section>
    <footer className="footer"><div className="container"><div className="footer-grid"><div><a className="brand" href="#home">AL-SHAHERYAR <span>ENTERPRISES</span></a><p>{company.descriptor}</p></div><div><h4>Quick links</h4><div className="footer-links"><a href="#home">Home</a><a href="#about">About</a><a href="#services">Services</a><a href="#products">Products</a><a href="#contact">Contact</a></div></div><div><h4>Contact</h4><a href={company.phoneHref}>{company.phoneDisplay}</a><p>Other business</p><a href={company.otherBusinessUrl}>{company.otherBusinessName}</a></div></div><div className="footer-bottom">© 2026 AL-SHAHERYAR ENTERPRISES. LPG service you can trust.</div></div></footer>
    <a className="float-wa" href={orderLink} aria-label="Order on WhatsApp"><Phone size={23} /></a><div className="mobile-bar"><a className="button red" href={orderLink}>WHATSAPP</a><a className="button" style={{ background: 'var(--dark)', color: '#fff' }} href={company.phoneHref}>CALL NOW</a></div>
  </main>;
}
